### PR TITLE
Release process

### PR DESCRIPTION
**Pull request by madsop-nav**
Inspired by several articles, mainly https://blog.stackademic.com/open-source-your-java-library-by-publishing-to-maven-central-using-github-actions-eb3989686fc4

Considered switching to JReleaser, but looks like the pom file is tailored at "manual" deploy already, so decided to stick to that way of doing it for now.

My idea is that every merge to main will trigger a new release, and that this is done automatically. Hence the use of timestamp as the version, as this can be updated automatically (and also strictly increasing).

There are several environment variables required for this:
- MAVEN_USERNAME
- MAVEN_CENTRAL_TOKEN
- MAVEN_GPG_PASSPHRASE
- GPG_PUBLIC_KEY
- GPG_SECRET_KEY

Those must be added into the secrets part of the repo or the organization (perhaps preferably the organization?). For the verification process on maven central, I also need help (or privileges) in creating a temporary repo under the organization.

(Destination branch will be main, but as I built this on top of the changed groupid, the changes are easier to see this way)

### CODE REVIEW

**Comment by madsop-nav** [comment]
Would especially like your input on this one, @imario42 , as you've done the release earlier on.

**Comment by imario42** [comment]
Personally I am more in the semver team than using timestamps as release number. Might also be possible: https://github.com/marketplace/actions/version-increment

About the "autorelease from main push": I am using gitlab with my work project where I have to click a button in the pipeline to really start the release from the main branch ... so I am more used to that final step, but sure, lets try to do it automatically.

**Comment by imario42** [comment]
@madsop-nav : I just changed the organisation so that you should be able to create the temporary repository you mentioned above. May I just ask why you need that? Haven't done the maven verification process for quite some time now ...

**Comment by madsop-nav** [comment]
> @madsop-nav : I just changed the organisation so that you should be able to create the temporary repository you mentioned above. May I just ask why you need that? Haven't done the maven verification process for quite some time now ...

Thanks!

In order to publish to Maven central, I first need to (as a one time thing) verify that I "own" this organization.

image

I expect to be able to add you and @siegelzc as owners there as well.

**Comment by imario42** [comment]
Nice! In https://github.com/openhtmltopdf/openhtmltopdf/pull/20/files you changed the group to org.openhtmltopdf, but we have to go with io.github.openhtmltopdf then, right?

**Comment by siegelzc** [comment]
This all looks good to me. I have no experience with any of this to give much useful commentary, but I at least read through the actions script and it all looks good to me.

I like the patch version increment. The automatic release doesn't bother me.

**Review by siegelzc — APPROVED** [review]

**Review by imario42 — APPROVED** [review]
I have no knowledge about github actions, but it looks good to me. Looking forward for the first release! :-)

**Comment by madsop-nav** [comment]
> Thank you all for your time on continuing maintenance of [openhtmltopdf](https://github.com/danfickle/openhtmltopdf)!
> 
> I would be very happy, if the changes in this PR can make it to a version on maven central soon, as I would like to switch to a maintained fork of [openhtmltopdf](https://github.com/danfickle/openhtmltopdf) and rather directly switch to the new group id.

Yes indeed, I think getting this one merged and properly working would be a milestone for us. The last few weeks have been rather hectic on my side, but I hope to get to this one either today/tomorrow or at least next week.

**Comment by imario42** [comment]
@madsop-nav I made you Admin for the repo!

**Comment by madsop-nav** [comment]
Aight, secrets set and I believe everything is properly configured (well, something's probably off, but I think it's time to merge and see)

**Pull request merged**
