### PR TITLE
Update PDFBox to 3.0.3

### PR DESCRIPTION
**Pull request by jochenberger**
See https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310760&version=12354416

### CODE REVIEW

**Comment by madsop-nav** [comment]
> Maybe we should enable Dependabot for the repository.

Yeah, I think that's a good idea as well. Feel free to setup an initial version or create an issue.

And thanks for the PR, merging now.

**Comment by jochenberger** [comment]
If I am not mistaken, Dependabot can be enabled in the repository settings.

**Comment by jonathansp** [comment]
@jochenberger @madsop-nav could you guys please publish this version to central maven?

**Comment by siegelzc** [comment]
> @jochenberger @madsop-nav could you guys please publish this version to central maven?

Looks like it was deployed on August 9.
https://repo1.maven.org/maven2/io/github/openhtmltopdf/openhtmltopdf-pdfbox/1.1.21/openhtmltopdf-pdfbox-1.1.21.pom
https://central.sonatype.com/artifact/io.github.openhtmltopdf/openhtmltopdf-pdfbox/versions

**Comment by madsop-nav** [comment]
> > @jochenberger @madsop-nav could you guys please publish this version to central maven?
> 
> Looks like it was deployed on August 9. https://repo1.maven.org/maven2/io/github/openhtmltopdf/openhtmltopdf-pdfbox/1.1.21/openhtmltopdf-pdfbox-1.1.21.pom https://central.sonatype.com/artifact/io.github.openhtmltopdf/openhtmltopdf-pdfbox/versions

Yup. For the record, @jonathansp , every commit to main results in a new version of the library, as described in https://github.com/openhtmltopdf/openhtmltopdf/discussions/36.

**Pull request merged**
